import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor configuration for TuBus Express native app.
 *
 * Strategy: the web bundle generated by `ng build --configuration production`
 * (output `dist/tubus-express/browser`) is wrapped 1:1 in a native WebView.
 * The same bundle that serves https://tubusexpress.com is what runs inside
 * the APK — zero divergence between web and native shells.
 *
 * `androidScheme: 'https'` ensures the WebView exposes a secure context,
 * which is required for Web Crypto, Notifications, and cookies behaving
 * the same as production web. Without this, Android would default to
 * `http://localhost` which breaks subtle browser APIs the SPA relies on.
 *
 * `allowNavigation` whitelists outbound origins the app can navigate to
 * via the WebView. Plain HTTP requests via fetch/XHR are NOT gated by this
 * (CORS handles those); this only restricts top-level navigations.
 */
const config: CapacitorConfig = {
  appId: 'com.tubusexpress.app',
  appName: 'TuBus Express',
  webDir: 'dist/tubus-express/browser',
  server: {
    androidScheme: 'https',
    allowNavigation: [
      'api.tubusexpress.com',
      'res.cloudinary.com',
      '*.googleusercontent.com',
      '*.firebaseio.com',
      '*.googleapis.com',
    ],
  },
  android: {
    // Solid background until web content paints. Matches the brand primary
    // color so the splash-to-content transition feels seamless.
    backgroundColor: '#001D56',
  },
};

export default config;
